### ISSUE TITLE
顧客登録機能　残考慮

### ISSUE THREAD

**Issue by tkykymok** [75ks/2022-server#17]
~●パスワード生成、メール送信
関根くんが実装済みの処理を取り込む~
→完了

●バリデーションチェック
・郵便番号に対するバリデーション　
→123-4567ではなく、1234567の形式でなければならない。
→placeholderの設定と、文字数チェック

・電話番号に対するバリデーション　
→090-1234-1234ではなく、 09012341234の形式でなければならない。
→placeholderの設定と、文字数チェック

・メールアドレスに対する存在チェック　ユニーク値でなければならない
→CUSTOMERテーブルに同じメールアドレスが存在するかチェックする処理を追加

・姓名　姓名カナに対するバリデーション
→文字数チェックを追加する。(テーブルに登録できる文字数は30文字)

**Comment by 75ks** [comment]
上記の対応が完了しましたので、クローズいたします。
